### ISSUE TITLE
Support Linux

### ISSUE THREAD

**Issue by marvhus** [judah-caruso/jai-sokol#3]
Could you add Linux bindings?

**Comment by judah-caruso** [comment]
I don't have a dedicated Linux machine right now, but it should be very easy for anyone to add Linux bindings. You can use `mac` as a reference. Really just need to add a `linux` directory + build script + the necessary `#library,no_dll "linux/sokol_xxx"` imports to each `sokol_xxx.jai` file.

**Comment by marvhus** [comment]
I'll see if I can add it in myself.

**Comment by marvhus** [comment]
@judah-caruso
I have added a `linux` directory with all the needed stuff, and I've added
```
else #if {
    #library,no_dll "linux/sokol_xxx";
}
``` 
to the needed files

but when I try the examples I get this error
```
In Workspace 2 ("Target Program"):
/home/mh/thirdparty/jai-sokol/examples/LearnOpenGL/../../module.jai:11,19: Error: #module_parameters can only be used in the toplevel scope of a module. Currently, this directive cannot be placed inside #if, a macro, or anywhere else weird.

    }
    #module_parameters(modules := Sokol_Modules.App | .Gfx | .Time | .Audio | .Color | .DebugText);
```

**Comment by marvhus** [comment]
changing
```
#load "../../module.jai"
```
to
```
#import,file "../../module.jai"
```
seams to fix it

**Comment by judah-caruso** [comment]
Closing as #4 was merged in.
